### ISSUE TITLE
laravel 8 support

### ISSUE THREAD

**Issue by maiconmva** [mehdi-fathi/eloquent-filter#116]
no work on laravel 8?

![image](https://user-images.githubusercontent.com/5194641/93125705-e62b8200-f6a1-11ea-82fe-167911cf861a.png)

**Comment by mehdi-fathi** [comment]
No, I didn't make an action test to be sure the eloquent filter is working in laravel 8. I am going to do it in days later.

**Comment by maiconmva** [comment]
one situation i didnt see, i can request fields i want select? like ?fields[]=user_name&fields[]=user_last_name

to no select all fields from model..

**Comment by mehdi-fathi** [comment]
@maiconmva read readme's repository again.

**Comment by jacob-hyde** [comment]
Please add Laravel 8 Support :)

**Comment by mehdi-fathi** [comment]
@jacob-hyde we had a problem in the mockery package in the laravel 8. I try my best to release the eloquent filter for the laravel 8. Please pray for me :)

**Comment by mehdi-fathi** [comment]
@jacob-hyde  @maiconmva  Good news the Laravel 8 supporting now eloquent filter. Please test it and if you have any problems tell me. The eloquent filter installs just in Laravel 8 prefer-stable.

**Comment by Kamleshpaul** [comment]
@mehdi-fathi  i m using in Laravel 8 and it working smoothly
