### ISSUE TITLE
WhereBetweenCondition fails if start or end is zero

### ISSUE THREAD

**Issue by elrasco** [mehdi-fathi/eloquent-filter#126]
**Describe the bug**
In file eloquent-filter/src/QueryFilter/Detection/ConditionsDetect/WhereBetweenCondition.php the condition fails if start or end is zero

**To Reproduce**
Pass to method detect something like 
`array (
  'price' => 
  array (
    'start' => 0,
    'end' => 336,
  )
)`

**Expected behavior**
detect returns WhereBetween::class

**Actual behavior**
detect return null

**Comment by mehdi-fathi** [comment]
@elrasco Thanks for the report. I fixed it. Please update the package to 2.3.8.

**Comment by elrasco** [comment]
@mehdi-fathi thank you very mauch. It works now. super fast.
