### ISSUE TITLE
Where Like and operators in nested relation

### ISSUE THREAD

**Issue by robsoncasousa** [mehdi-fathi/eloquent-filter#134]
**Is your feature request related to a problem? Please describe.**
First of all I want to congratulate you for the great job you did here.
I wish I could use operators and where like in nested relation, like this:
- select * from users ... ... join posts ...  where posts.title like '%program%'
- select * from users ... ... join posts ...  where posts.views > 100
Kind of "posts[title][like]=%program%" but eloquentFilter expects "like" be a column: posts.title.like.

**Describe the solution you'd like**
So I was thinking about the last item of the column param be the operator:
posts[title][like]=%program%  => posts.title like '%program%'
posts[views][=]=100  => posts.views = 100
posts[views][>]=100  => posts.views > 100

What do you think about it?

**Comment by mehdi-fathi** [comment]
@robsoncasousa you should read https://github.com/mehdi-fathi/eloquent-filter#Custom-Detection-Condition for more details. Believe I couldn't make all of the features that you need just I can make a clean structure for implementing your need.
you can use of custom-detection-Condition or custom query in this case. read more readme file.

Thanks

**Comment by robsoncasousa** [comment]
Ok, I'll do it. Thanks!
