### ISSUE TITLE
Installation on Laravel 8 / PHP 8

### ISSUE THREAD

**Issue by aeadedoyin** [mehdi-fathi/eloquent-filter#142]
Installation on Laravel 8, PHP 8

![image](https://user-images.githubusercontent.com/20503883/106594603-9f57ff00-6552-11eb-9b08-f14bfebfa488.png)

**Comment by mehdi-fathi** [comment]
@aeadedoyin Eloquent filter has been stable for near 3 months. Your problem isn't related to the eloquent filter.

**Comment by aeadedoyin** [comment]
Since there was no other package that implement filter very simple as this package, had to do a bit of research on installation challenges in composer packages, for anyone having this issue here are two options for you:

**Option 1:**
Delete /composer.lock file then add `"mehdi-fathi/eloquent-filter": "^2.4"`  to the /composer.json and run
```
compose install
```

**Option 2: (faster)**
```
composer require mehdi-fathi/eloquent-filter --ignore-platform-reqs
```
