### ISSUE TITLE
Support for DB Query Builder

### ISSUE THREAD

**Issue by vicenterusso** [mehdi-fathi/eloquent-filter#143]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I would like to be able to use filters with the Query builder, not just Eloquent

**Describe alternatives you've considered**
I have not found any alternatives

**Comment by mehdi-fathi** [comment]
@vicenterusso Good idea. I think about it.

**Comment by vicenterusso** [comment]
Should we expect this to be implemented ?

**Comment by mehdi-fathi** [comment]
@vicenterusso No, because we have the complexity to implement this feature. Also, this feature is not common among users. So I couldn't implement this feature now.
