### ISSUE TITLE
Multiple OrderBy

### ISSUE THREAD

**Issue by elreco** [mehdi-fathi/eloquent-filter#144]
Hello! 

Thank you for this plugin. 

Can we make a query with multiple order by please?

**Comment by mehdi-fathi** [comment]
@elreco 
Hello
The current version hasn't multiple order_by. But I think I could add this feature to the next version. I will try to add it. In fact, you can add this by use of the custom method.

**Comment by mehdi-fathi** [comment]
@elreco update composer and read readme

**Comment by elreco** [comment]
Thank you!
