### ISSUE TITLE
Column not found: 1054 Unknown column '0' in 'where clause

### ISSUE THREAD

**Issue by Kamleshpaul** [mehdi-fathi/eloquent-filter#148]
**when we pass extra param which are not present in `AcceptRequest()`**
this is my code
```php
ControlPanel::AcceptRequest([
            'id',
            'name',
            'description',
            'theme',
            'created_at',
            'updated_at',
        ])->filter();
```

now here if i pass some extra field which is not present in this list like `?foo=baar` it throw below error

**Error**
>SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select count(*) as aggregate from `control_panels` where `0` = id and `1` = name and `2` = description and `3` = theme and `4` = created_at and `5` = updated_at) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select count(*) as aggregate from `control_panels` where `0` = id and `1` = name and `2` = description and `3` = theme and `4` = created_at and `5` = updated_at) at /var/www/html/dcc-repository/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)

i m using 

```
"mehdi-fathi/eloquent-filter": "^2.4.5",
```
with laravel 8 

> __NOTE__ - it is working fine in  `2.4.0`  version

**Comment by mehdi-fathi** [comment]
@Kamleshpaul Thanks for this report. I fixed please update to the 2.4.6 version.
