### ISSUE TITLE
It's hard to understand the features of this package.

### ISSUE THREAD

**Issue by devbapidey** [mehdi-fathi/eloquent-filter#153]
I have to filter my table with differently on different parameter. I read readmd, now unsure why this package created. It's not working for me. Documentation is not explaining how it works.

**Comment by mehdi-fathi** [comment]
@devbapidey Eloquent filter has been released for more than 2 years. You are the only person that says `Documentation is not explaining how it works`. I can't help you. I just suggest reading article medium https://medium.com/@mehdifathi.developer/introduce-eloquent-filter-2-in-laravel-21bfb35195e9

**Comment by devbapidey** [comment]
Well it works! Just mistake elsewhere. Thank you for amazing eloquent-filter.
