### ISSUE TITLE
Where the nested relation Model dose not work properly with inertiajs.

### ISSUE THREAD

**Issue by devbapidey** [mehdi-fathi/eloquent-filter#154]
laravel 8.33
eloquent-filter 2.4.6

I am using eloquent-filter with inertiajs. Now using array query string like this item[price] is not possible in .vue file. I have to convert it to a string like 'item[price]'.

So my final method in vue file look like this
`methodName(){
  this.$inertia.get({
    data: {
      item[price]: this.item.price,
    },
  })
}`

But problem is when I select different price it send **&item[price]=100&item[price]=200**
and this is default behavior of inertiajs, Which I don't want. Is it possible to use different identifier for nested relation Model?

**Comment by mehdi-fathi** [comment]
@devbapidey You can make a new array before the filter and pass it to the filter method.
