### ISSUE TITLE
ignoreRequest sets "deleted_at is null"

### ISSUE THREAD

**Issue by ClProsser** [mehdi-fathi/eloquent-filter#165]
**Describe the bug**
I try to filter on a model including trashed entries. This works as designed, however, adding `ignoreRequest()` adds `where deleted_at is null` to the query, which is definitely not intended. I don't see any reason why especially `ignoreRequest` should add that. 

**To Reproduce**
1. Add a filter to a query including trashed entries (`::withTrashed()`). The result includes trashed entries (if exist).
2. Add `ignoreRequest()` to the builder. The result does not include trashed entries anymore.

Here is some boilerblade code:
```php
dump($request->input());
dump(Vehicle::withTrashed()->filter()->toSql());
dump(Vehicle::withTrashed()->ignoreRequest(["id"])->toSql()); //ignoring id for demonstration
dd(Vehicle::withTrashed()->ignoreRequest(["id"])->filter()->toSql());
```
The result:
```
array:1 [
  "id" => "1"
]
```
```
"select * from `vehicles` where `id` = ?"
```
```
"select * from `vehicles` where `vehicles`.`deleted_at` is null"
```
```
"select * from `vehicles` where `vehicles`.`deleted_at` is null"
```

**Expected behavior**
I expect that calling `ignoreRequest()` does not modify the query in that way (i.e. only fields listed as argument should be ignored).

**Workaround**
Just remove the desired field (which should be ignored) from the request and add it again afterwards. 

```php
$id = $request->input("id");
$request->request->remove("id");
$vehicles = Vehicle::withTrashed()->filter()->get(); //Cannot call ignoreRequest(['rent']) as else filtered by deleted_at

//Add it back to make default laravel functions work properly
$request->request->add([
    'id' => $id
]);
dd($vehicles);
```

**Versions:**
 - Laravel: v8.27.0
 - Your Eloquent Filter: v2.4.4
 - PHP: v7.4.11

**Additional context**
I tried this in a fresh laravel project as well, just to confirm my observation.

**Comment by mehdi-fathi** [comment]
@ClProsser I should check it and make a unit test for this situation as soon. I'll announce you. Thanks for report

**Comment by ClProsser** [comment]
@mehdi-fathi Sounds great, thanks for the quick reply and the amazing package

**Comment by ClProsser** [comment]
@mehdi-fathi looks like it works now (my tests are passing). Thanks for the quick fix, keep going :)
