### ISSUE TITLE
Use custom exceptions for better error handling

### ISSUE THREAD

**Issue by MirazMac** [mehdi-fathi/eloquent-filter#175]
**Is your feature request related to a problem? Please describe.**
The package often throws exception which is very good for error handling and debugging. But catching or handling those exceptions are kind of problematic. Since the package only throws `\Exception`,  it's hard to catch them by their specific name as all exceptions extend this base `Exception` class. 
So it would be good if those exceptions were custom made.

**Describe the solution you'd like**
Create and throw custom exception classes that extend the base `\Exception` class. For example, `EloquentFilterException` etc. So, one can simply do this:

```php
try {
//...
} catch (\eloquentFilter\Exceptions\EloquentFilterException $e) {
} catch(\AnyOtherException $e) {
}
```

Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by mehdi-fathi** [comment]
@MirazMac 

Good, suggest. I'll investigate this feature in the later version.

Thanks

**Comment by MirazMac** [comment]
Thanks a lot.

**Comment by mehdi-fathi** [comment]
@MirazMac Please upgrade the package to 2.5.4

**Comment by MirazMac** [comment]
I just did, thanks a lot for such quick action.
