### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by frankyso** [mehdi-fathi/eloquent-filter#189]
Thank you for your amazing package, :)

can you please release it for laravel 9 sir?

**Comment by mehdi-fathi** [comment]
@frankyso 

I don't have enough time but I try to add supporting laravel 9 this month.

**Comment by frankyso** [comment]
I have create a PR before can you pls check that? 

https://github.com/mehdi-fathi/eloquent-filter/pull/188

**Comment by mehdi-fathi** [comment]
@frankyso 

It's not easy as you think. we use Action GitHub to pass some tests and I have to change some tests for this purpose.

**Comment by mehdi-fathi** [comment]
@frankyso 
Support laravel 9 has been added.

**Comment by frankyso** [comment]
thank youu
