### ISSUE TITLE
Add date function to the  where query for created_at/updated_at and other TIMESTAMP columns

### ISSUE THREAD

**Issue by MirazMac** [mehdi-fathi/eloquent-filter#194]
**Is your feature request related to a problem? Please describe.**
One of the problems I'm facing right now while using this is, whenever I try to  use the conditions on **TIMESTAMP**  fields:

For example:
**?created_at[operator]==&created_at[value]=2022-07-14**

This will generate this query:

```sql
select * from `contents` where  `created_at` = '2022-07-14'
```

And since Laravel stores the **created_at** field as a **TIMESTAMP** column, the query won't return any result.

On the other hand, Eloquent's ``whereDate()`` scope works, as it generates this query:

```sql
select * from `contents` where date(`created_at`) = '2022-07-14'
```

**Describe the solution you'd like**

My suggestion is to use the ``date()`` function to the where query just like Eloquent's ``whereDate()`` does, if the column's name are created_at / updated_at. Or perhaps this can be set in a model property for any other fields like:

```php 
public static array $filterUseDate = ['created_at'];
```

Great package btw. Thanks.

**Comment by mehdi-fathi** [comment]
@MirazMac 
Hi
Thanks for letting me know the issue. sadly, I didn't have enough time to fix it. But You can solve your problem by use of other features such as a custom query or a Custom detection.

**Comment by MirazMac** [comment]
> @MirazMac Hi Thanks for letting me know the issue. sadly, I didn't have enough time to fix it. But You can solve your problem by use of other features such as a custom query or a Custom detection.

It's alright. I'm using Custom Detection to achieve this. I just added this a suggestion, it would be nice to have it built in for DATE/DATETIME columns. That's all.

**Comment by mehdi-fathi** [comment]
@MirazMac 
Added to new version
