### ISSUE TITLE
Wrong instructions for publishing the configuration file on README.md

### ISSUE THREAD

**Issue by marcoaureliocardoso** [mehdi-fathi/eloquent-filter#198]
**Describe the bug**
Wrong instructions for publishing the configuration file.

**To Reproduce**
1. On console: `php artisan vendor:publish --provider="eloquentFilter\EloquentFilterServiceProvider"`
 Results : **INFO  No publishable resources for tag [].**

**Expected behavior**
Publish the configuration file.

**Screenshots**
![image](https://user-images.githubusercontent.com/9138786/203577100-ef9c4363-3b4b-4916-a86e-d3357facb321.png)

**Desktop:**
 - OS: Ubuntu 22.04.1 LTS on Windows 10 WSL
 - Laravel framework v9.41.0 with PHP 8.1.2-1ubuntu2.8 (cli) - Zend Engine v4.1.2
 - Browser: Chrome v107.0.5304.107 64 bits

**Additional context**
On README.md:
![image](https://user-images.githubusercontent.com/9138786/203578912-38d7ae30-21db-4902-8f1f-be894bcffb21.png)

**Comment by mehdi-fathi** [comment]
@marcoaureliocardoso 
Thanks for reporting I'll fix it later version
