### ISSUE TITLE
Target class [eloquentFilter] does not exist.

### ISSUE THREAD

**Issue by arislanhaikal** [mehdi-fathi/eloquent-filter#199]
**Describe the bug**
I have followed step by step, but after doing the filter it shows up
`Target class [eloquentFilter] does not exist.`

**To Reproduce**
Steps to reproduce the behavior using **Laravel 9, PHP 8**:
1. Install
2. Add provider and alias to app.php
3. Add trait Filterable in model
4. Add filter() -> User::filter()->get();

Has anyone have some issue?

**Comment by mehdi-fathi** [comment]
@arislanhaikal 
Thanks, for let me know it has been fixed now and you need to run composer update
