### ISSUE TITLE
Add Laravel 10 Support

### ISSUE THREAD

**Issue by MirazMac** [mehdi-fathi/eloquent-filter#200]
**Is your feature request related to a problem? Please describe.**
This package can't be installed to Laravel 10, currently due to conflicting dependency versions.

**Describe the solution you'd like**
To update the dependency versions to make it installable on Laravel 10.

**Describe alternatives you've considered**

**Additional context**
Laravel 10 has released recently.

**Comment by mehdi-fathi** [comment]
@MirazMac 

Thanks for reminding
added on 3.1.0 version support PHP 8.1, 8.2, and Laravel 10.x

**Comment by MirazMac** [comment]
> @MirazMac
> 
> Thanks for reminding added on 3.1.0 version support PHP 8.1, 8.2, and Laravel 10.x

Great work as always. Thanks!
