### ISSUE TITLE
Deprecated on PHP 8.2

### ISSUE THREAD

**Issue by AnthonyLedru** [mehdi-fathi/eloquent-filter#202]
**Describe the bug**
It seems there is deprecated notice appearing with the new warnings implemented in php 8.1/8.2

https://www.php.net/manual/fr/migration81.deprecated.php
https://www.php.net/manual/en/migration82.deprecated.php

**To Reproduce**
Use the query() method on any filterable model

**Expected behavior**
No warning

**Additional context**

 ```DEPRECATED  Calling static trait method eloquentFilter\QueryFilter\Core\HelperFilter::isAssoc is deprecated, it should only be called on a class using the trait in vendor/mehdi-fathi/eloquent-filter/src/QueryFilter/Detection/ConditionsDetect/Eloquent/WhereInCondition.php on line 22.```

**Comment by mehdi-fathi** [comment]
@AnthonyLedru 

Thanks for informing me. It is fixed at 3.3.9.
