### ISSUE TITLE
Latest version is not working.

### ISSUE THREAD

**Issue by enuenan** [mehdi-fathi/eloquent-filter#206]
I have installed 4.*.* .  And included my searchable columns in whiteListFilter array. In the form I have used name="search". while searching it kept saying to add search to whiteListFilter. After so many days of hard working I have found out it is version issue. Now I have installed **3.4** and it's working for me.

**Comment by mehdi-fathi** [comment]
@enuenan 
I doubt it because not only do we have various tests but also I've installed this package on Laravel in the latest version. anyway, I'm excited to hear about your issue in detail.
