### ISSUE TITLE
Where Like %admin% Not Working

### ISSUE THREAD

**Issue by sunghangga** [mehdi-fathi/eloquent-filter#207]
**Bug description**
"where like" query doesn't work only for word %admin% . I have sent directly sql query to database with "select * from users like '%admin%'" and it will show users contains "admin" in the name, but not with eloquent-filter.

**Step to reproduce**
1. Do request with "where like" params, for example: {{urll}}/api/auth/users?name[like]=%admin%.
2. Result: no data found.

**Expected behavior**
Data containing word "admin" appears.

**Comment by mehdi-fathi** [comment]
@sunghangga 

Not only I didn't consider any limitation on the word but also we have strong unit tests that have to do with all types of queries. I suggest reviewing your code from scratch.
