### ISSUE TITLE
Support for Laravel 11?

### ISSUE THREAD

**Issue by arislanhaikal** [mehdi-fathi/eloquent-filter#210]
Please add support for Laravel 11. And how i can config it?

Thank you

**Comment by mehdi-fathi** [comment]
@arislanhaikal 

Since Laravel 11 was released freshly, It seems some dependency packages are not working with the process of testing the eloquent filter. We need to wait until we find a better opportunity to support that.

**Comment by arislanhaikal** [comment]
Oh, i'm sorry to hear that. Hopefully find the best solution, because your filter package really helped me 🙏🏻

**Comment by mehdi-fathi** [comment]
@arislanhaikal 

Supporting Laravel 11 has been solved so you can update to 4.2.0 version.

**Comment by arislanhaikal** [comment]
Hi @mehdi-fathi thank you for fast working it

But i have some issue,

With step
- Iam already instal version 4.2.0 & registered in service provider
- make `php artisan eloquentFilter:filter UserFilter`
- add trait in user model Filterable, UserFilter
- in UserFilter, I make name query search with function `name`
- in Controller, I add `User::filter()->`
- i tested but not working with error
- `You must set name in whiteListFilter in User or create an override method with name name or call ignoreRequest method for ignore name.`

I dont know this is issue or not, but in old version its just work fine!
Please explain whether there are any steps missed!

Thank you

**Comment by mehdi-fathi** [comment]
@arislanhaikal 
You need to change the method to filterCustomName. I'll fix the artisan command soon.

**Comment by MLDMoritz** [comment]
> @arislanhaikal You need to change the method to filterCustomName. I'll fix the artisan command soon.

I came along this issue today, it took a bit research to fix this.
