### ISSUE TITLE
eloquent-filter doesn't work Laravel 7.4

### ISSUE THREAD

**Issue by paduanton** [mehdi-fathi/eloquent-filter#64]
I have a new project that is based on Laravel 7.4 and when I run the command to add eloquent-filter dependency, it crashes:
**To Reproduce**
Running the comand inside a Laravel 7.4 project:
`composer require mehdi-fathi/eloquent-filter`

Errors:
02:04 $ composer require mehdi-fathi/eloquent-filter
Using version ^1.6 for mehdi-fathi/eloquent-filter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
    - mehdi-fathi/eloquent-filter 1.6.0 requires illuminate/pagination 5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^6.1 -> satisfiable by illuminate/pagination[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44.........
- don't install illuminate/pagination v6.7.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.8.0|don't install laravel/framework v7.4.0
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].
    - Installation request for mehdi-fathi/eloquent-filter ^1.6 -> satisfiable by mehdi-fathi/eloquent-filter[1.6.0, 1.6.0.x-dev].

If you think I'm doing something wrong, please tell me. Let's talk about it

**Comment by mehdi-fathi** [comment]
I've made some changes to increase stability on laravel 7.x. but I don't release that. I release eloquent filter 6.2 for laravel 7.x today because of you. Thanks for your response if you have any idea about this package I like to hear that.

**Comment by paduanton** [comment]
Nice, thank you. It's working like a charm.

**Comment by olipiskandar** [comment]
pardon me..
i got same erro on laravel 7.4..
how to resolve this error ?

**Comment by mehdi-fathi** [comment]
@olipiskandar eloquent-filter has no problem in laravel 7.x.I've checked by ci test also @paduanton has no problem by that.you can run again `composer require mehdi-fathi/eloquent-filter`

**Comment by olipiskandar** [comment]
still not work..
Using version ^1.6 for mehdi-fathi/eloquent-filter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
    - mehdi-fathi/eloquent-filter 1.6.0 requires illuminate/pagination 5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^6.1 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/pagination[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - mehdi-fathi/eloquent-filter 1.6.0.x-dev requires illuminate/pagination 5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^6.1 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/pagination[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[5.5.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.4.0].
    - don't install illuminate/pagination 6.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.0.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.0.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.0.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.0.3|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.0.4|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.1.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.10.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.11.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.12.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.13.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.13.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.14.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.15.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.15.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.16.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.17.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.17.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.18.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.18.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.18.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.18.3|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.2.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.3.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.4.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.5.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.5.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.5.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.6.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.6.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.6.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.7.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v6.8.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.5.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.6.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.7.17|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.7.18|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.7.19|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.7.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination 5.8.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.16|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.17|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.28|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.33|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.34|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.35|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.36|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.37|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.39|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.40|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.41|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.43|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.5.44|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.10|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.11|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.12|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.13|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.14|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.15|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.16|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.17|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.19|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.20|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.21|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.22|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.23|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.24|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.25|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.26|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.27|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.28|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.29|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.3|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.30|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.31|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.32|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.33|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.34|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.35|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.36|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.37|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.38|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.39|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.4|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.5|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.6|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.7|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.8|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.6.9|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.1|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.10|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.11|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.15|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.20|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.21|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.22|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.23|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.26|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.27|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.28|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.3|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.4|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.5|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.6|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.7|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.8|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.7.9|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.0|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.11|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.12|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.14|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.15|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.17|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.18|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.19|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.2|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.20|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.22|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.24|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.27|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.28|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.29|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.3|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.30|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.31|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.32|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.33|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.34|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.35|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.36|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.4|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.8|don't install laravel/framework v7.4.0
    - don't install illuminate/pagination v5.8.9|don't install laravel/framework v7.4.0
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].
    - Installation request for mehdi-fathi/eloquent-filter ^1.6 -> satisfiable by mehdi-fathi/eloquent-filter[1.6.0, 1.6.0.x-dev].

**Comment by mehdi-fathi** [comment]
@olipiskandar you were installing version 1.6. Version 1.6.0 is not stable on laravel 7.x you must install eloquent-filter version 1.6.2. If you run composer install you should change version eloquent filter in composer.json.**version 1.6.2 is just for laravel 7.x**

**Comment by olipiskandar** [comment]
hello..
this is my composer.json
"require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/helpers": "^1.2",
        "laravel/scout": "^8.0",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "laravelium/feed": "^7.0",
        "livewire/livewire": "^1.0",
        "mehdi-fathi/eloquent-filter": "1.6.2",
        "realrashid/sweet-alert": "^3.1",
        "santigarcor/laratrust": "^5.2",
        "teamtnt/laravel-scout-tntsearch-driver": "^8.1",
        "unisharp/laravel-filemanager": "~1.9.2"
    },
if i run composer install :
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.

if i run composer update :
Problem 1
    - The requested package mehdi-fathi/eloquent-filter 1.6.2 exists as mehdi-fathi/eloquent-filter[1.0.0, 1.0.1, 1.0.2, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.3.0, 1.3.2, 1.4.0, 1.4.1, 1.4.1.x-dev, 1.4.2, 1.4.3, 1.5.0, 1.5.0.x-dev, 1.5.1, 1.5.1.x-dev, 1.5.2, 1.5.2.x-dev, 1.5.3, 1.5.3.x-dev, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.6.0, 1.6.0.x-dev, dev-add-stickler-config, dev-analysis-3wWojA, dev-analysis-86WAgl, dev-analysis-8A0Vw9, dev-analysis-8AZ3Dl, dev-analysis-8LWdA6, dev-analysis-8bw3e2, dev-analysis-8mQ51V, dev-analysis-KZoo76, dev-analysis-Px5ZNP, dev-analysis-Vrjnl6, dev-analysis-XWOeZP, dev-analysis-XZV7JD, dev-analysis-XZV7eg, dev-analysis-XaPGJo, dev-analysis-Xk1bxJ, dev-analysis-XkGPe1, dev-analysis-ajVmmB, dev-analysis-q1Vobv, dev-analysis-qMmmnl, dev-analysis-qvAA4x, dev-analysis-qyyvdN, dev-analysis-z922wP, dev-analysis-zEZawD, dev-analysis-zOwneB, dev-analysis-zRB9wp, dev-analysis-zYGJR9, dev-analysis-zerKYP, dev-master, dev-mehdi-dev, dev-mehdi-fathi-patch-1, dev-mehdi-fathi-working, dev-mehdi-fathi-working-2, dev-mehdi-fathi-working-4, dev-mehdi-travic-ci, dev-revert-2-master, v1.1] but these are rejected by your constraint.

**Comment by mehdi-fathi** [comment]
@olipiskandar your composer has a problem.delete composer.lock if docsn't work delete vendor folder and run composer install.
