### ISSUE TITLE
ignoreRequest

### ISSUE THREAD

**Issue by laymont** [mehdi-fathi/eloquent-filter#81]
First, sorry by me english!!

**Describe the bug**
You must set **perpage** in whiteListFilter in **model**.php or create a override method with name **perpage** or call **ignoreRequest** function for ignore perpage

**To Reproduce**
My code:
```
public function index()
{
Model::ignoreRequest(['links','meta','page','perpage'])->orderBy('id', 'Desc')->MyScope()->filter()->paginate()->appends(request()->query());
}
```

**Comment by mehdi-fathi** [comment]
@laymont I've tested.that's ok.eloquent filter doesn't have any problem with this code. probably you are made mistake in MyScope method.

**Comment by laymont** [comment]
My Scope
```
public function scopeEnInventario($query)
    {
        return $query->where('inout', 0);
    }
```
and without scope retrieve same error:
**You must set perpage in whiteListFilter in InventarioV2.php or create a override method with name perpage or call ignoreRequest function for ignore perpage.**

**Comment by laymont** [comment]
My Scope
```
public function scopeEnInventario($query)
    {
        return $query->where('inout', 0);
    }
```
and without scope retrieve same error:
**You must set perpage in whiteListFilter in InventarioV2.php or create a override method with name perpage or call ignoreRequest function for ignore perpage.**

**Comment by mehdi-fathi** [comment]
@laymont You must first call scopeEnInventario and later use filter method.

**Comment by laymont** [comment]
same, friend
```
InventarioV2Resource::collection(InventarioV2::EnInventario()->ignoreRequest(['links','meta','page','perpage'])->orderBy('id', 'Desc')->filter()->paginate()->appends(request()->query()));
```
![image](https://user-images.githubusercontent.com/13275422/85166127-d92efc00-b234-11ea-9603-f3d92835b16c.png)

**Comment by mehdi-fathi** [comment]
ignoreRequest is a scope you must call static

**Comment by laymont** [comment]
```
**InventarioV2::ignoreRequest(['links','meta','page','per_page'])->EnInventario()->orderBy('id', 'Desc')->filter()....**
```
same :-(

**Comment by mehdi-fathi** [comment]
I think you don’t familiar with eloquent.you should try it without your custom scope.

**Comment by laymont** [comment]
**right now implement the following code:**
Make a Helpers:
```
function removeRequestForEloquentFilter(Request $request)
{
    $request->request->remove('links');
    $request->request->remove('meta');
    $request->request->remove('meta');
    $request->request->remove('per_page');
}
```

```
removeRequestForEloquentFilter($request);
return InventarioV2Resource::collection(InventarioV2::ignoreRequest(['links','meta','page','per_page'])->EnInventario()->orderBy('id', 'Desc')->filter()->paginate()->appends(request()->query()));
```
**It worked!**

**Comment by laymont** [comment]
solved! The order must be respected. Next model calls ignore static request, then filter and then the scope, paginate or query.
Thanks @mehdi-fathi
