### ISSUE TITLE
Or Where

### ISSUE THREAD

**Issue by Laygendev** [mehdi-fathi/eloquent-filter#90]
Hi Everybody,

How can we use orWhere ? i'm trying to get an entity by name or by firstname 2 and i cant make request like:

SELECT * FROM product WHERE name=1 OR firstname=2

**Describe the solution you'd like**
For now I add in QueryFilterBuilder.php whereOr method:

```
/**
     * @param       $field
     * @param array $params
     */
    public function whereOr($field, array $params)
    {
        $this->builder->orWhere("$field", $params['or']);
    }
```

And a case in QueryBuilder.php in the method: "detectMethodByParams":

```
private function detectMethodByParams($field, $params)
    {
        if (!empty($params['start']) && !empty($params['end'])) {
            $method = 'whereBetween';
        } elseif (!empty($params['operator']) && !empty($params['value'])) {
            $method = 'whereByOpt';
        } elseif (!empty($params['like'])) {
            $method = 'like';
        } elseif (!empty($params['or'])) { // HERE
            $method = 'whereOr';
        } elseif (is_array($params) && !$this->isAssoc($params)) {
            $method = 'whereIn';
        } elseif (stripos($field, '.')) {
            $method = 'wherehas';
        } elseif (is_string($params)) {
            $method = 'where';
        }

        return $method ?? null;
    }
```

Maybe we can already make a query for that, i'm waiting for your answer!

Thanks a lot for this package!

**Comment by mehdi-fathi** [comment]
@Laygendev Hi
You can make a custom query filter for this job. But i think this feature can will be to next version. I will work to this feature soon.Also you can to add this feature and i will review your code just your code must has a test for accepting merge.
Thanks for this idea
