### ISSUE TITLE
Supporting hasManyThrough filtering?

### ISSUE THREAD

**Issue by orenlande** [mehdi-fathi/eloquent-filter#96]
Hello Mehdi,

I've been developing more and more using your library. Recently, I've stumbled upon the following issue:

**Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\HasManyThrough::filter()**

I'm using hasManyThrough relationship on this specific resource, and looks like the libaray has difficulties to handle the request. Do you know why it happens? any workarounds with it?

Thank you!

**Comment by mehdi-fathi** [comment]
@orenlande 

Hello 

 I didn't write a code for this feature. In fact, I can't make all features in the core eloquent filter. so you can write a custom filter for this purpose. you can implement this feature and i accept your merge if you wrote a unit test for that.

Thanks

**Comment by orenlande** [comment]
I see, thanks. I'll work on it.

Can you briefly explain to me how should I implement it? I'm not very familiar with how to inject the filter method into core classes (in our case - the HasManyThrough class).

Thanks!

**Comment by mehdi-fathi** [comment]
@orenlande The eloquent filter has a class with the name 'QueryFilterBuilder'. Every query has been generated in this class. You can code in whereas method. I suggest first make a unit test after you implement this feature(sample test whereas is in the ModelFilterMockTest.php).
